spring.application.name=coffeelike
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/coffee
spring.datasource.username=postgres
spring.datasource.password=634138170s3250HD2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect